production:
  host: capellapauta.com.br
  port: 9010
  pid_file: log/ferret.pid
development:
  host: capellapauta.com.br
  port: 9010
  pid_file: log/ferret.pid
test:
  host: capellapauta.com.br
  port: 9009
  pid_file: log/ferret.pid
